/**
 * THE SINGLE SOURCE OF TRUTH for the journal format.
 *
 * `header` must match the column heading in the Google Sheet exactly.
 * Editing this file is the only code change needed to add/remove/rename a column —
 * it drives the sheet headings, the AI's response schema, and the review form.
 *
 * source:
 *   "ai"      – extracted from what the user wrote
 *   "derived" – calculated by the app; never asked for, never AI-guessed
 */

export type FieldType = "text" | "number" | "enum" | "date" | "time";
export type FieldSource = "ai" | "derived";

/** Section headings in the review form, in display order. */
export const GROUPS = [
  "Trade",
  "Prices",
  "Size",
  "Context",
  "Psychology",
  "Outcome",
  "Notes",
  "Auto",
] as const;

export type Group = (typeof GROUPS)[number];

export interface Field {
  /** Machine-safe key used inside the app. */
  key: string;
  /** Exact column heading in the sheet. */
  header: string;
  type: FieldType;
  source: FieldSource;
  group: Group;
  /** Allowed values for `type: "enum"`. Enforced by the AI response schema. */
  values?: readonly string[];
  /** Explains the field to the AI. Written for a model, not for a human. */
  desc: string;
  /** Longer input box in the review form. */
  long?: boolean;
}

export const FIELDS = [
  // ── Identity & time ────────────────────────────────────────────────
  { key: "tradeId", header: "Trade ID", type: "text", source: "derived", group: "Auto",
    desc: "Unique id generated by the app." },
  { key: "date", header: "Date", type: "date", source: "ai", group: "Trade",
    desc: "Date the trade was taken, YYYY-MM-DD. If not stated, today." },
  { key: "time", header: "Time", type: "time", source: "ai", group: "Trade",
    desc: "Time the position was opened, 24h HH:mm. Null if not stated." },
  { key: "timezone", header: "Timezone", type: "text", source: "derived", group: "Auto",
    desc: "Always IST." },
  { key: "weekNumber", header: "Week Number", type: "number", source: "derived", group: "Auto",
    desc: "ISO week number, from the date." },
  { key: "month", header: "Month", type: "text", source: "derived", group: "Auto",
    desc: "Month name, from the date." },
  { key: "year", header: "Year", type: "number", source: "derived", group: "Auto",
    desc: "Year, from the date." },

  // ── Instrument & direction ─────────────────────────────────────────
  { key: "asset", header: "Asset", type: "text", source: "ai", group: "Trade",
    desc: "Plain name of what was traded, e.g. Gold, Nifty, Bitcoin, EURUSD." },
  { key: "symbol", header: "Symbol", type: "text", source: "ai", group: "Trade",
    desc: "Ticker if identifiable. gold/xau → XAUUSD, nifty → NIFTY, btc → BTCUSD. Null if unclear." },
  { key: "direction", header: "Buy / Sell", type: "enum", source: "ai", group: "Trade",
    values: ["BUY", "SELL"],
    desc: "BUY for bought/long/longed/bullish. SELL for sold/short/shorted/bearish." },

  // ── Prices ─────────────────────────────────────────────────────────
  { key: "entryPrice", header: "Entry Price", type: "number", source: "ai", group: "Prices",
    desc: "Price the position was opened at." },
  { key: "exitPrice", header: "Exit Price", type: "number", source: "ai", group: "Prices",
    desc: "Price the position was closed at. If they say price hit target, this equals the target. If they say stopped out, this equals the stop loss." },
  { key: "stopLoss", header: "Stop Loss", type: "number", source: "ai", group: "Prices",
    desc: "Stop loss price. Null if none was set." },
  { key: "target", header: "Target", type: "number", source: "ai", group: "Prices",
    desc: "Take profit price. Null if no target was set." },
  { key: "riskReward", header: "Risk Reward", type: "number", source: "derived", group: "Auto",
    desc: "Reward divided by risk, from entry/stop/target." },

  // ── Size ───────────────────────────────────────────────────────────
  { key: "lotSize", header: "Lot Size", type: "number", source: "ai", group: "Size",
    desc: "Lots, contracts, quantity or units as stated." },
  { key: "positionSize", header: "Position Size", type: "number", source: "ai", group: "Size",
    desc: "Notional value if explicitly stated. Null otherwise — never estimate it." },

  // ── Context ────────────────────────────────────────────────────────
  { key: "session", header: "Session", type: "enum", source: "ai", group: "Context",
    values: ["ASIA", "LONDON", "NEW YORK", "OVERLAP", "OTHER"],
    desc: "Trading session if stated or clearly implied (e.g. 'London open' → LONDON)." },
  { key: "marketCondition", header: "Market Condition", type: "text", source: "ai", group: "Context",
    desc: "e.g. trending, ranging, choppy, volatile, news-driven. Only if described." },
  { key: "setupName", header: "Setup Name", type: "text", source: "ai", group: "Context",
    desc: "Named setup, e.g. liquidity sweep, order block, breakout retest, FVG." },
  { key: "strategy", header: "Strategy Used", type: "text", source: "ai", group: "Context",
    desc: "Broader strategy or system, if named separately from the setup." },
  { key: "reasonForEntry", header: "Reason for Entry", type: "text", source: "ai", group: "Context",
    desc: "Why they entered, in their own words, condensed to one line.", long: true },
  { key: "reasonForExit", header: "Reason for Exit", type: "text", source: "ai", group: "Context",
    desc: "Why they exited, e.g. hit target, stopped out, closed manually.", long: true },

  // ── Psychology ─────────────────────────────────────────────────────
  { key: "emotionBefore", header: "Emotion Before Trade", type: "text", source: "ai", group: "Psychology",
    desc: "Emotion before entering, only if mentioned." },
  { key: "emotionDuring", header: "Emotion During Trade", type: "text", source: "ai", group: "Psychology",
    desc: "Emotion while in the trade, only if mentioned." },
  { key: "emotionAfter", header: "Emotion After Trade", type: "text", source: "ai", group: "Psychology",
    desc: "Emotion after closing, only if mentioned." },
  { key: "confidence", header: "Confidence Rating", type: "number", source: "ai", group: "Psychology",
    desc: "Confidence 1-10, only if a number is stated or clearly implied." },
  { key: "ruleBroken", header: "Rule Broken", type: "text", source: "ai", group: "Psychology",
    desc: "Any personal trading rule they say they broke. Their words, not your judgement." },

  // ── Outcome ────────────────────────────────────────────────────────
  { key: "result", header: "Result", type: "enum", source: "derived", group: "Auto",
    values: ["WIN", "LOSS", "BE"],
    desc: "From stated PnL, or from entry vs exit vs direction." },
  { key: "pnl", header: "PnL", type: "number", source: "ai", group: "Outcome",
    desc: "Profit or loss in money, only if stated. Negative for a loss. Never calculate it." },
  { key: "pnlPercent", header: "PnL %", type: "number", source: "ai", group: "Outcome",
    desc: "Percent gain/loss on the account, only if stated." },
  { key: "holdingTime", header: "Holding Time", type: "text", source: "ai", group: "Outcome",
    desc: "How long the trade was held, only if stated, e.g. '45m', '2h 10m'." },

  // ── Attachments & notes ────────────────────────────────────────────
  { key: "tradingViewLink", header: "TradingView Link", type: "text", source: "ai", group: "Notes",
    desc: "TradingView URL if one appears in the text." },
  { key: "lessonsLearned", header: "Lessons Learned", type: "text", source: "ai", group: "Notes",
    desc: "What they say they learned or would do differently.", long: true },
  { key: "notes", header: "Additional Notes", type: "text", source: "ai", group: "Notes",
    desc: "Anything meaningful that fits no other column. Do not repeat other fields here.", long: true },

  { key: "createdAt", header: "Created Timestamp", type: "text", source: "derived", group: "Auto",
    desc: "When this row was written, IST." },
] as const satisfies readonly Field[];

/** Column headings, in sheet order. Row 1 of the sheet is exactly this. */
export const HEADERS: string[] = FIELDS.map((f) => f.header);

/** The fields the AI is asked to fill in. Derived ones are computed, never guessed. */
export const AI_FIELDS = FIELDS.filter((f) => f.source === "ai");

export type FieldKey = (typeof FIELDS)[number]["key"];

/** A trade as the app passes it around. Every value optional — blank is always allowed. */
export type TradeRow = Partial<Record<FieldKey, string | number | null>>;

/**
 * Turn a trade into a row array ordered by the sheet's ACTUAL headers.
 *
 * This is the header-driven mapping from ARCHITECTURE.md §3: we never assume the
 * sheet's column order matches FIELDS. If a column was moved or renamed by hand,
 * values still land under the right heading, and unknown headings get left blank.
 */
export function toRow(trade: TradeRow, sheetHeaders: string[]): (string | number)[] {
  const byHeader = new Map<string, FieldKey>(
    FIELDS.map((f) => [f.header.toLowerCase(), f.key as FieldKey]),
  );

  return sheetHeaders.map((heading) => {
    const key = byHeader.get(heading.trim().toLowerCase());
    if (!key) return "";
    const value = trade[key];
    return value === null || value === undefined ? "" : value;
  });
}
